services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
    - 11434:11434
    volumes:
    - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
    - shared-net
  qdrant:
  
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
    - 6333:6333
    - 6334:6334
    volumes:
    - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
    - shared-net
volumes:
  ollama-data: null
  qdrant-data: null
networks:
  shared-net:
    external: true
